// Code generate by sfindex. DO NOT EDIT.
package sfgo

type Attribute uint32

const (
ARRAY_INT  Attribute = 0
ARRAY_STR  Attribute = 0
ARRAY_ANY  Attribute = 0

SF_REC_TYPE Attribute = ARRAY_INT // 0
//Type name:  SFHeader
SFHE_VERSION_INT Attribute = SF_REC_TYPE + 1 	// 1
SFHE_EXPORTER_STR Attribute = ARRAY_STR 		// 0
SFHE_IP_STR Attribute = SFHE_EXPORTER_STR + 1 	// 1
SFHE_FILENAME_STR Attribute = SFHE_IP_STR + 1 	// 2

//Type name:  Container
CONT_ID_STR Attribute = SFHE_FILENAME_STR + 1			// 3
CONT_NAME_STR Attribute = CONT_ID_STR + 1				// 4
CONT_IMAGE_STR Attribute = CONT_NAME_STR + 1			// 5
CONT_IMAGEID_STR Attribute = CONT_IMAGE_STR + 1			// 6
CONT_TYPE_INT Attribute = SFHE_VERSION_INT + 1			// 2
CONT_PRIVILEGED_INT Attribute = CONT_TYPE_INT + 1		// 3
CONT_PODID_STRING_STR Attribute = CONT_IMAGEID_STR + 1	// 7

//Type name:  Pod
POD_TS_INT Attribute = CONT_PRIVILEGED_INT + 1			// 4
POD_ID_STR Attribute = CONT_PODID_STRING_STR + 1		// 8
POD_NAME_STR Attribute = POD_ID_STR + 1					// 9
POD_NODENAME_STR Attribute = POD_NAME_STR + 1			// 10
POD_HOSTIP_STR Attribute = POD_NODENAME_STR + 1			// 11
POD_HOSTIP_ANY Attribute = ARRAY_ANY					// 0
POD_INTERNALIP_STR Attribute = POD_HOSTIP_STR + 1		// 12
POD_INTERNALIP_ANY Attribute = POD_HOSTIP_ANY + 1		// 1
POD_NAMESPACE_STR Attribute = POD_INTERNALIP_STR + 1	// 13
POD_RESTARTCOUNT_INT Attribute = POD_TS_INT + 1			// 5
POD_SERVICES_STR Attribute = POD_NAMESPACE_STR + 1		// 14
POD_SERVICES_ANY Attribute = POD_INTERNALIP_ANY + 1		// 2

//Type name:  K8sEvent
K8SE_KIND_INT Attribute = POD_RESTARTCOUNT_INT + 1		// 6
K8SE_ACTION_INT Attribute = K8SE_KIND_INT + 1			// 7
K8SE_TS_INT Attribute = K8SE_ACTION_INT + 1				// 8
K8SE_MESSAGE_STR Attribute = POD_SERVICES_STR + 1		// 15

//Type name:  Process
PROC_STATE_INT Attribute = K8SE_TS_INT + 1						// 9
PROC_OID_CREATETS_INT Attribute = PROC_STATE_INT + 1			// 10	
PROC_OID_HPID_INT Attribute = PROC_OID_CREATETS_INT + 1			// 11
PROC_POID_CREATETS_INT Attribute = PROC_OID_HPID_INT + 1		// 12
PROC_POID_HPID_INT Attribute = PROC_POID_CREATETS_INT + 1		// 13
PROC_TS_INT Attribute = PROC_POID_HPID_INT + 1					// 14
PROC_EXE_STR Attribute = K8SE_MESSAGE_STR + 1					// 16
PROC_EXEARGS_STR Attribute = PROC_EXE_STR + 1					// 17
PROC_UID_INT Attribute = PROC_TS_INT + 1						// 15
PROC_USERNAME_STR Attribute = PROC_EXEARGS_STR + 1				// 18
PROC_GID_INT Attribute = PROC_UID_INT + 1						// 16
PROC_GROUPNAME_STR Attribute = PROC_USERNAME_STR + 1			// 19
PROC_TTY_INT Attribute = PROC_GID_INT + 1						// 17
PROC_CONTAINERID_STRING_STR Attribute = PROC_GROUPNAME_STR + 1	// 20
PROC_ENTRY_INT Attribute = PROC_TTY_INT + 1						// 18

//Type name:  File
FILE_STATE_INT Attribute = PROC_ENTRY_INT + 1					// 19
FILE_OID_STR Attribute = PROC_CONTAINERID_STRING_STR + 1		// 21
FILE_TS_INT Attribute = FILE_STATE_INT + 1						// 20
FILE_RESTYPE_INT Attribute = FILE_TS_INT + 1					// 21
FILE_PATH_STR Attribute = FILE_OID_STR + 1						// 22
FILE_CONTAINERID_STRING_STR Attribute = FILE_PATH_STR + 1		// 23

//Type name:  FileEvent
EV_FILE_TS_INT Attribute = FILE_RESTYPE_INT + 1					// 22
EV_FILE_TID_INT Attribute = EV_FILE_TS_INT + 1					// 23
EV_FILE_CAP_EFFECTIVE_STR = 27									// 27
EV_FILE_CAP_PERMITTED_STR = 28									// 28
EV_FILE_CAP_INHERITABLE_STR = 29								// 29
EV_FILE_OPFLAGS_INT Attribute = EV_FILE_TID_INT + 1
EV_FILE_RET_INT Attribute = EV_FILE_OPFLAGS_INT + 1

//Type name:  File  number 2
SEC_FILE_STATE_INT Attribute = EV_FILE_RET_INT + 1
SEC_FILE_OID_STR Attribute = FILE_CONTAINERID_STRING_STR + 1
SEC_FILE_TS_INT Attribute = SEC_FILE_STATE_INT + 1
SEC_FILE_RESTYPE_INT Attribute = SEC_FILE_TS_INT + 1
SEC_FILE_PATH_STR Attribute = SEC_FILE_OID_STR + 1
SEC_FILE_CONTAINERID_STRING_STR Attribute = SEC_FILE_PATH_STR + 1

//Type name:  FileFlow
FL_FILE_TS_INT Attribute = FILE_RESTYPE_INT + 1
FL_FILE_TID_INT Attribute = FL_FILE_TS_INT + 1
FL_FILE_CAP_EFFECTIVE_STR = 27
FL_FILE_CAP_PERMITTED_STR = 28
FL_FILE_CAP_INHERITABLE_STR = 29
FL_FILE_OPFLAGS_INT Attribute = FL_FILE_TID_INT + 1
FL_FILE_ENDTS_INT Attribute = FL_FILE_OPFLAGS_INT + 1
FL_FILE_FD_INT Attribute = FL_FILE_ENDTS_INT + 1
FL_FILE_NUMRRECVOPS_INT Attribute = FL_FILE_FD_INT + 1
FL_FILE_NUMWSENDOPS_INT Attribute = FL_FILE_NUMRRECVOPS_INT + 1
FL_FILE_NUMRRECVBYTES_INT Attribute = FL_FILE_NUMWSENDOPS_INT + 1
FL_FILE_NUMWSENDBYTES_INT Attribute = FL_FILE_NUMRRECVBYTES_INT + 1
FL_FILE_OPENFLAGS_INT Attribute = FL_FILE_NUMWSENDBYTES_INT + 1

//Type name:  NetworkFlow
FL_NETW_TS_INT Attribute = FILE_RESTYPE_INT + 1
FL_NETW_TID_INT Attribute = FL_NETW_TS_INT + 1
FL_NETW_CAP_EFFECTIVE_STR = 27
FL_NETW_CAP_PERMITTED_STR = 28
FL_NETW_CAP_INHERITABLE_STR = 29
FL_NETW_OPFLAGS_INT Attribute = FL_NETW_TID_INT + 1
FL_NETW_ENDTS_INT Attribute = FL_NETW_OPFLAGS_INT + 1
FL_NETW_FD_INT Attribute = FL_NETW_ENDTS_INT + 1
FL_NETW_NUMRRECVOPS_INT Attribute = FL_NETW_FD_INT + 1
FL_NETW_NUMWSENDOPS_INT Attribute = FL_NETW_NUMRRECVOPS_INT + 1
FL_NETW_NUMRRECVBYTES_INT Attribute = FL_NETW_NUMWSENDOPS_INT + 1
FL_NETW_NUMWSENDBYTES_INT Attribute = FL_NETW_NUMRRECVBYTES_INT + 1
FL_NETW_SIP_INT Attribute = FL_NETW_NUMWSENDBYTES_INT + 1
FL_NETW_SPORT_INT Attribute = FL_NETW_SIP_INT + 1
FL_NETW_DIP_INT Attribute = FL_NETW_SPORT_INT + 1
FL_NETW_DPORT_INT Attribute = FL_NETW_DIP_INT + 1
FL_NETW_PROTO_INT Attribute = FL_NETW_DPORT_INT + 1

//Type name:  ProcessEvent
EV_PROC_TS_INT Attribute = FILE_RESTYPE_INT + 1
EV_PROC_TID_INT Attribute = EV_PROC_TS_INT + 1
EV_PROC_CAP_EFFECTIVE_STR = 27
EV_PROC_CAP_PERMITTED_STR = 28
EV_PROC_CAP_INHERITABLE_STR = 29
EV_PROC_OPFLAGS_INT Attribute = EV_PROC_TID_INT + 1
EV_PROC_RET_INT Attribute = EV_PROC_OPFLAGS_INT + 1

INT_ARRAY_SIZE Attribute = 35 + 1
STR_ARRAY_SIZE Attribute = 29 + 1
ANY_ARRAY_SIZE Attribute = 2 + 1
)

